import type { GetTaskResponse } from '../../src/http-client.js'

export function makeTimelineFixture(): GetTaskResponse {
  return {
    task: {
      taskId: 'T-TIMELINE',
      projectId: 'agent-spaces',
      workflow: { id: 'code_defect_fastlane', version: 1, hash: 'sha256:workflow' },
      state: { status: 'active', phase: 'green' },
      version: 1,
      goal: 'show the task story',
      roleBindings: {
        implementer: { kind: 'agent', id: 'cody' },
        tester: { kind: 'agent', id: 'rex' },
      },
      createdAt: '2026-05-11T05:29:09.000Z',
      updatedAt: '2026-05-11T05:32:22.000Z',
    },
    events: [
      {
        eventId: 'wevt_1',
        workflowSeq: 1,
        schemaVersion: 1,
        taskId: 'T-TIMELINE',
        workflow: { id: 'code_defect_fastlane', version: 1, hash: 'sha256:workflow' },
        type: 'task.created',
        commandType: 'task.create',
        actor: { kind: 'agent', id: 'clod' },
        observedTaskVersion: 0,
        idempotencyKey: 'create',
        result: 'accepted',
        payload: {},
        commandHash: 'sha256:command-1',
        eventHash: 'sha256:event-1',
        createdAt: '2026-05-11T05:29:09.000Z',
      },
      {
        eventId: 'wevt_2',
        workflowSeq: 2,
        schemaVersion: 1,
        taskId: 'T-TIMELINE',
        workflow: { id: 'code_defect_fastlane', version: 1, hash: 'sha256:workflow' },
        type: 'evidence.attached',
        commandType: 'evidence.attach',
        actor: { kind: 'agent', id: 'cody' },
        role: 'implementer',
        observedTaskVersion: 0,
        idempotencyKey: 'evidence',
        result: 'accepted',
        payload: { evidenceId: 'evd_1', kind: 'tdd_green_bundle', ref: 'memo:T/green' },
        commandHash: 'sha256:command-2',
        prevHash: 'sha256:event-1',
        eventHash: 'sha256:event-2',
        createdAt: '2026-05-11T05:29:55.000Z',
      },
      {
        eventId: 'wevt_3',
        workflowSeq: 3,
        schemaVersion: 1,
        taskId: 'T-TIMELINE',
        workflow: { id: 'code_defect_fastlane', version: 1, hash: 'sha256:workflow' },
        type: 'transition.rejected',
        commandType: 'transition.rejected',
        actor: { kind: 'agent', id: 'clod' },
        role: 'implementer',
        observedTaskVersion: 0,
        idempotencyKey: 'reject',
        result: 'rejected',
        rejectionCode: 'version_conflict',
        payload: { transitionId: 'red_to_green' },
        commandHash: 'sha256:command-3',
        prevHash: 'sha256:event-2',
        eventHash: 'sha256:event-3',
        createdAt: '2026-05-11T05:30:23.000Z',
      },
      {
        eventId: 'wevt_4',
        workflowSeq: 4,
        schemaVersion: 1,
        taskId: 'T-TIMELINE',
        workflow: { id: 'code_defect_fastlane', version: 1, hash: 'sha256:workflow' },
        type: 'transition.applied',
        commandType: 'transition.accepted',
        actor: { kind: 'agent', id: 'cody' },
        role: 'implementer',
        observedTaskVersion: 0,
        nextTaskVersion: 1,
        idempotencyKey: 'accept',
        result: 'accepted',
        payload: {
          transitionId: 'red_to_green',
          from: { status: 'open', phase: 'red' },
          to: { status: 'active', phase: 'green' },
        },
        commandHash: 'sha256:command-4',
        prevHash: 'sha256:event-3',
        eventHash: 'sha256:event-4',
        createdAt: '2026-05-11T05:30:57.000Z',
      },
      {
        eventId: 'wevt_5',
        workflowSeq: 5,
        schemaVersion: 1,
        taskId: 'T-TIMELINE',
        workflow: { id: 'code_defect_fastlane', version: 1, hash: 'sha256:workflow' },
        type: 'participant_run.launched',
        commandType: 'participant.run.admitted',
        actor: { kind: 'agent', id: 'cody' },
        role: 'implementer',
        participantRunId: 'prun_1',
        observedTaskVersion: 1,
        idempotencyKey: 'run',
        result: 'accepted',
        payload: { runId: 'prun_1', role: 'implementer' },
        commandHash: 'sha256:command-5',
        prevHash: 'sha256:event-4',
        eventHash: 'sha256:event-5',
        createdAt: '2026-05-11T05:31:32.000Z',
      },
      {
        eventId: 'wevt_6',
        workflowSeq: 6,
        schemaVersion: 1,
        taskId: 'T-TIMELINE',
        workflow: { id: 'code_defect_fastlane', version: 1, hash: 'sha256:workflow' },
        type: 'workflow_hrc_run.mapped',
        commandType: 'workflow.hrc_run.mapped',
        actor: { kind: 'agent', id: 'cody' },
        participantRunId: 'prun_1',
        observedTaskVersion: 1,
        idempotencyKey: 'run',
        result: 'recorded',
        payload: {
          mapId: 'whrc_1',
          hrcRunId: 'hrc-run-1',
          scopeRef: 'cody@agent-spaces:T-TIMELINE',
        },
        commandHash: 'sha256:command-6',
        prevHash: 'sha256:event-5',
        eventHash: 'sha256:event-6',
        createdAt: '2026-05-11T05:32:22.000Z',
      },
    ],
    evidence: [
      {
        evidenceId: 'evd_1',
        taskId: 'T-TIMELINE',
        kind: 'tdd_green_bundle',
        ref: 'memo:T/green',
        actor: { kind: 'agent', id: 'cody' },
        role: 'implementer',
        createdAt: '2026-05-11T05:29:55.000Z',
      },
    ],
    obligations: [],
    effects: [],
    supervisorRuns: [],
    participantRuns: [
      {
        runId: 'prun_1',
        kind: 'participant',
        taskId: 'T-TIMELINE',
        workflow: { id: 'code_defect_fastlane', version: 1, hash: 'sha256:workflow' },
        actor: { kind: 'agent', id: 'cody' },
        role: 'implementer',
        status: 'launched',
        taskVersionAtStart: 1,
        contextHash: 'sha256:context',
        createdAt: '2026-05-11T05:31:32.000Z',
      },
    ],
    workflowHrcRunMaps: [
      {
        mapId: 'whrc_1',
        workflowTaskId: 'T-TIMELINE',
        participantRunId: 'prun_1',
        hrcRunId: 'hrc-run-1',
        scopeRef: 'cody@agent-spaces:T-TIMELINE',
        laneRef: 'main',
        createdAt: '2026-05-11T05:32:22.000Z',
        source: 'launch',
      },
    ],
    anomalies: [],
    workflowPatchProposals: [],
  }
}
