#!/usr/bin/env bun
/**
 * check-cli-surface - self-describing surface conformance for the acp CLI.
 *
 * The public-surface guard already derives the live Commander tree. This focused
 * gate binds the documented README inventory to that same live surface:
 *
 *   1. every documented command path must exist in Commander;
 *   2. every visible Commander command path must be documented;
 *   3. every documented long option must exist on that command;
 *   4. every long option declared on a command must be documented.
 *
 * Exit 0 = conformant. Exit 1 = docs/live CLI drift, with concrete fix guidance.
 */

import { readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Command } from 'commander'

import { buildProgram } from '../packages/acp-cli/src/cli.js'

type CliEntry = {
  path: string
  description?: string
  flags: string[]
}

type FindingKind =
  | 'documented-command-absent'
  | 'present-command-undocumented'
  | 'documented-flag-absent'
  | 'present-flag-undocumented'

type Finding = {
  source: string
  kind: FindingKind
  token: string
  detail: string
}

type Options = {
  root: string
  write: boolean
}

const repoRoot = resolve(fileURLToPath(new URL('..', import.meta.url)))
const readmeRel = 'packages/acp-cli/README.md'
const beginMarker = '<!-- BEGIN ACP CLI SURFACE -->'
const endMarker = '<!-- END ACP CLI SURFACE -->'

function sorted(values: Iterable<string>): string[] {
  return [...new Set(values)].sort((a, b) => a.localeCompare(b))
}

function parseArgs(argv: string[]): Options {
  const options: Options = { root: repoRoot, write: false }
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index]
    if (arg === '--root') {
      index += 1
      if (argv[index] === undefined) throw new Error('--root requires a path')
      options.root = resolve(argv[index])
    } else if (arg === '--write') {
      options.write = true
    } else if (arg === '--help' || arg === '-h') {
      console.log('Usage: bun scripts/check-cli-surface.ts [--root <path>] [--write]')
      process.exit(0)
    } else {
      throw new Error(`unknown argument: ${arg}`)
    }
  }
  return options
}

function optionFlags(command: Command): string[] {
  return sorted(
    command.options.flatMap((option) =>
      option.flags
        .split(/[ ,|]+/)
        .filter((flag) => flag.startsWith('--'))
        .map((flag) => flag.replace(/[<[].*$/, ''))
    )
  )
}

function collectCommandEntries(command: Command, prefix: string[] = []): CliEntry[] {
  const current = [...prefix, command.name()]
  const own = {
    path: current.join(' '),
    description: command.description(),
    flags: optionFlags(command),
  }
  const children = command
    .createHelp()
    .visibleCommands(command)
    .filter((child) => child.name() !== 'help')
    .flatMap((child) => collectCommandEntries(child, current))
  return [own, ...children]
}

function buildCliSurface(): CliEntry[] {
  return collectCommandEntries(buildProgram({}, []))
}

function renderSurfaceBlock(entries: CliEntry[]): string {
  const lines = entries.map((entry) => {
    const flags = entry.flags.length === 0 ? '-' : entry.flags.join(' ')
    return `${entry.path} | ${flags}`
  })
  return [
    beginMarker,
    '',
    '```text',
    '# Generated by: bun scripts/check-cli-surface.ts --write',
    '# Format: command path | long options declared on that command; - means none',
    ...lines,
    '```',
    '',
    endMarker,
  ].join('\n')
}

function replaceSurfaceBlock(readme: string, block: string): string {
  const begin = readme.indexOf(beginMarker)
  const end = readme.indexOf(endMarker)
  if (begin !== -1 && end !== -1 && end > begin) {
    return `${readme.slice(0, begin)}${block}${readme.slice(end + endMarker.length)}`
  }
  return `${readme.trimEnd()}\n\n## Mechanical CLI Surface\n\n${block}\n`
}

function parseDocumentedSurface(source: string, text: string): CliEntry[] {
  const begin = text.indexOf(beginMarker)
  const end = text.indexOf(endMarker)
  if (begin === -1 || end === -1 || end <= begin) {
    throw new Error(`${source}: missing ${beginMarker} / ${endMarker} inventory block`)
  }

  const entries: CliEntry[] = []
  const block = text.slice(begin + beginMarker.length, end)
  block.split('\n').forEach((line, index) => {
    const trimmed = line.trim()
    if (
      trimmed.length === 0 ||
      trimmed === '```text' ||
      trimmed === '```' ||
      trimmed.startsWith('#')
    ) {
      return
    }

    const match = trimmed.match(/^(acp(?:\s+[a-z][a-z0-9-]*)*)\s+\|\s+(.+)$/)
    if (match === null) {
      throw new Error(`${source}:${index + 1}: invalid CLI surface entry: ${trimmed}`)
    }
    const flags = match[2] === '-' ? [] : sorted(match[2].split(/\s+/).filter(Boolean))
    for (const flag of flags) {
      if (!/^--[a-z][a-z0-9-]*$/.test(flag)) {
        throw new Error(`${source}:${index + 1}: invalid long option token: ${flag}`)
      }
    }
    entries.push({ path: match[1], flags })
  })
  return entries
}

function toMap(entries: CliEntry[]): Map<string, Set<string>> {
  return new Map(entries.map((entry) => [entry.path, new Set(entry.flags)]))
}

function compareSurfaces(actual: CliEntry[], documented: CliEntry[], source: string): Finding[] {
  const actualMap = toMap(actual)
  const documentedMap = toMap(documented)
  const findings: Finding[] = []

  for (const path of sorted(documentedMap.keys())) {
    if (!actualMap.has(path)) {
      findings.push({
        source,
        kind: 'documented-command-absent',
        token: path,
        detail: 'The README documents an acp command path that is not in the live Commander tree.',
      })
    }
  }

  for (const path of sorted(actualMap.keys())) {
    if (!documentedMap.has(path)) {
      findings.push({
        source,
        kind: 'present-command-undocumented',
        token: path,
        detail:
          'The live Commander tree exposes an acp command path missing from the README inventory.',
      })
    }
  }

  for (const path of sorted(actualMap.keys())) {
    const actualFlags = actualMap.get(path)
    const documentedFlags = documentedMap.get(path)
    if (actualFlags === undefined || documentedFlags === undefined) continue

    for (const flag of sorted(documentedFlags)) {
      if (!actualFlags.has(flag)) {
        findings.push({
          source,
          kind: 'documented-flag-absent',
          token: `${path} ${flag}`,
          detail:
            'The README documents a long option that this Commander command does not declare.',
        })
      }
    }

    for (const flag of sorted(actualFlags)) {
      if (!documentedFlags.has(flag)) {
        findings.push({
          source,
          kind: 'present-flag-undocumented',
          token: `${path} ${flag}`,
          detail:
            'The live Commander command declares a long option missing from the README inventory.',
        })
      }
    }
  }

  return findings
}

function fixFor(finding: Finding): string {
  switch (finding.kind) {
    case 'documented-command-absent':
      return 'FIX: remove or rename the stale README command entry, or restore the reviewed command intentionally.'
    case 'present-command-undocumented':
      return 'FIX: run `bun scripts/check-cli-surface.ts --write` after reviewing the new command as public CLI surface.'
    case 'documented-flag-absent':
      return 'FIX: remove or rename the stale README flag entry, or restore the reviewed option intentionally.'
    case 'present-flag-undocumented':
      return 'FIX: run `bun scripts/check-cli-surface.ts --write` after reviewing the new option as public CLI surface.'
  }
}

function report(findings: Finding[]): void {
  for (const finding of findings) {
    console.error(`- [${finding.kind}] ${finding.source}`)
    console.error(`  token: ${finding.token}`)
    console.error(`  why: ${finding.detail}`)
    console.error(`  ${fixFor(finding)}`)
  }
}

async function collectFindings(root = repoRoot): Promise<Finding[]> {
  const readmePath = join(root, readmeRel)
  const readme = await readFile(readmePath, 'utf8')
  return compareSurfaces(
    buildCliSurface(),
    parseDocumentedSurface(readmeRel, readme),
    `${readmeRel} ${beginMarker}`
  )
}

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2))
  const readmePath = join(options.root, readmeRel)
  const readme = await readFile(readmePath, 'utf8')
  const actual = buildCliSurface()

  if (options.write) {
    await writeFile(readmePath, replaceSurfaceBlock(readme, renderSurfaceBlock(actual)))
    console.log(`check-cli-surface: wrote ${readmeRel}`)
    return
  }

  const documented = parseDocumentedSurface(readmeRel, readme)
  const findings = compareSurfaces(actual, documented, `${readmeRel} ${beginMarker}`)
  if (findings.length > 0) {
    console.error(`check-cli-surface: ${findings.length} acp CLI docs/live drift(s):`)
    report(findings)
    process.exit(1)
  }

  console.log('check-cli-surface: acp README command and flag inventory matches Commander')
}

export {
  buildCliSurface,
  collectFindings,
  compareSurfaces,
  parseDocumentedSurface,
  renderSurfaceBlock,
  type CliEntry,
  type Finding,
}

if (import.meta.main) {
  await main()
}
