const WRKF_ERROR_HTTP_STATUS: Record<string, number> = {
  WRKF_NOT_FOUND: 404,
  WRKF_ROLE_DENIED: 403,
  WRKF_STALE_REVISION: 409,
  WRKF_CONTEXT_MISMATCH: 409,
  WRKF_IDEMPOTENCY_MISMATCH: 409,
  WRKF_LEASE_CONFLICT: 409,
  WRKF_TRANSITION_BLOCKED: 422,
  WRKF_VALIDATION: 422,
  WRKF_EFFECT_NOT_DELIVERABLE: 422,
  WRKF_DB_MIGRATION_REQUIRED: 503,
  WRKF_INTERNAL: 500,
  WRKF_UNAVAILABLE: 503,
}

export function wrkfErrorToHttpStatus(code: string): number {
  return WRKF_ERROR_HTTP_STATUS[code] ?? 500
}
